export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const EMAIL_SEND_CODE_REQUEST = 'EMAIL_SEND_CODE_REQUEST'

export const EMAIL_SEND_CODE_SUCCESS = 'EMAIL_SEND_CODE_SUCCESS'

export const EMAIL_SEND_CODE_FAIL = 'EMAIL_SEND_CODE_FAIL'

export const EMAIL_CHECK_CODE_REQUEST = 'EMAIL_CHECK_CODE_REQUEST'

export const EMAIL_CHECK_CODE_SUCCESS = 'EMAIL_CHECK_CODE_SUCCESS'

export const EMAIL_CHECK_CODE_FAIL = 'EMAIL_CHECK_CODE_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'